version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  aptcopilot:
    image: joshadambell43/aptcopilot
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=/etc/db_password
      - DB_SERVER=aptcopilot-test.ck7rzkuy8vhb.us-west-1.rds.amazonaws.com:3306
      - DB_NAME=aptcopilot_test
    labels:
      - traefik.backend=aptcopilot
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.main.frontend.rule=Host:aptcopilot.com
      - traefik.main.port=8000
    networks:
      - proxy
    ports:
     - 8000:8000

  traefik:
    image: traefik:1.4.5-alpine
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/ubuntu/traefik.toml:/traefik.toml
     - /home/ubuntu/acme.json:/acme.json
    ports:
     - 80:80
     - 443:443
    labels:
     - traefik.frontend.rule=Host:monitor.aptcopilot.com
     - traefik.port=8080
    networks:
     - proxy
    environment:
     - AWS_ACCESS_KEY_ID=
     - AWS_SECRET_ACCESS_KEY=
     - AWS_REGION=us-west-2