defaultEntryPoints = ["http", "https"]

logLevel = "DEBUG"

[web]
address = ":8080"
  [web.auth.basic]
  users = ["<password>"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "joshadambell@me.com"
storage = "acme.json"
dnsProvider = "route53"
entryPoint = "https"
onHostRule = true
onDemand = false
acmeLogging = true

[docker]
domain = "aptcopilot.com"
watch = true
exposedbydefault = false